import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

const config: Config = {
  title: 'คู่มือการใช้งาน EPIC',
  tagline: 'คู่มือ EPIC ทุกรุ่น — อ่านออนไลน์ ภาษาไทย/อังกฤษ',
  favicon: 'img/favicon.ico',

  future: {
    v4: true,
  },

  // Production URL — Cloudflare Pages custom domain
  url: 'https://manual.mssiv.com',
  baseUrl: '/',

  plugins: [
    function trackingPlugin() {
      return {
        name: 'docusaurus-tracking-plugin',
        injectHtmlTags() {
          return {
            headTags: [
              {
                tagName: 'script',
                attributes: {},
                innerHTML: `
                  !function(f,b,e,v,n,t,s)
                  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
                  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
                  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
                  n.queue=[];t=b.createElement(e);t.async=!0;
                  t.src=v;s=b.getElementsByTagName(e)[0];
                  s.parentNode.insertBefore(t,s)}(window, document,'script',
                  'https://connect.facebook.net/en_US/fbevents.js');
                  fbq('init', '1945045202488164');
                  fbq('init', '1559528578876193');
                `,
              },
              {
                tagName: 'script',
                attributes: {
                  async: 'true',
                  src: 'https://www.googletagmanager.com/gtag/js?id=G-8B5L058716',
                },
              },
              {
                tagName: 'script',
                attributes: {},
                innerHTML: `
                  window.dataLayer = window.dataLayer || [];
                  function gtag(){dataLayer.push(arguments);}
                  window.gtag = gtag;
                  gtag('js', new Date());
                  gtag('config', 'G-8B5L058716', { send_page_view: false });
                  gtag('config', 'AW-958250070');
                `,
              },
            ],
            preBodyTags: [
              {
                tagName: 'noscript',
                attributes: {},
                innerHTML: `
                  <img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=1945045202488164&ev=PageView&noscript=1" />
                  <img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=1559528578876193&ev=PageView&noscript=1" />
                `,
              },
            ],
          };
        },
      };
    },
  ],

  clientModules: [
    require.resolve('./src/clientModules/tracking.ts'),
  ],

  trailingSlash: false,

  organizationName: 'mssiv',
  projectName: 'manual-mssiv',

  onBrokenLinks: 'warn',

  // TH default (ลูกค้าไทย), EN secondary
  i18n: {
    defaultLocale: 'th',
    locales: ['th', 'en'],
    localeConfigs: {
      th: {
        label: 'ภาษาไทย',
        direction: 'ltr',
        htmlLang: 'th-TH',
      },
      en: {
        label: 'English',
        direction: 'ltr',
        htmlLang: 'en-US',
      },
    },
  },

  presets: [
    [
      'classic',
      {
        docs: {
          path: 'docs', // TH default locale
          routeBasePath: '/', // clean URLs: /, /es-k70/intro, /catalog
          sidebarPath: './sidebars.ts',
          showLastUpdateTime: false,
          async sidebarItemsGenerator({
            defaultSidebarItemsGenerator,
            item,
            ...args
          }) {
            const sidebarItems = await defaultSidebarItemsGenerator({
              item,
              ...args
            });
            if (item.type === 'autogenerated') {
              const dirName = item.dirName;
              return sidebarItems.filter(
                (child: any) => !(child.type === 'doc' && child.id === `${dirName}/intro`)
              );
            }
            return sidebarItems;
          },
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    docs: {
      sidebar: {
        autoCollapseCategories: true,
      },
    },
    colorMode: {
      defaultMode: 'light',
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'EPIC Manuals',
      logo: {
        alt: 'EPIC',
        src: 'img/epic-logo.svg',
      },
      items: [
        {to: '/catalog', label: 'คู่มือทั้งหมด', position: 'left'},
        {
          type: 'localeDropdown',
          position: 'right',
        },
        {
          href: 'https://epicdoorlock.com',
          label: 'epicdoorlock.com ↗',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'EPIC Manuals',
          items: [
            {label: 'คู่มือทั้งหมด', to: '/catalog'},
            {label: 'English Version', href: 'pathname:///en/catalog'},
          ],
        },
        {
          title: 'EPIC',
          items: [
            {label: 'เว็บไซต์ทางการ', href: 'https://www.epic.co.kr'},
            {label: 'epicdoorlock.com', href: 'https://epicdoorlock.com'},
            {label: 'LINE @epicdoorlock', href: 'https://line.me/R/ti/p/@epicdoorlock'},
            {label: 'Facebook', href: 'https://fb.com/epicdoorlock'},
          ],
        },
      ],
      copyright: `Copyright © 2026 Massive System Co.,Ltd. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
