import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const PRODUCT_MANUALS = [
  'es-k70',
  'es-303g',
  'es-b10',
  'es-l200',
  'es-m50',
  'es-t153',
  'es-p9100fk',
  'es-809l',
  'ef-8000l',
  'ef-p8800k',
  'n-touch',
  'touch',
  'os300h',
  'popscan',
  'triplex-2way',
  'triplex-3way',
  'es-s100dr',
  'es-f300dr',
  'es-f301d',
  'es-f501d',
  'es-ff730gr',
  'es-ff731g',
  'es-s740d',
  'es-f7000kr',
  'es-f9000kr',
  'es-p8800k',
];

const REFERENCE_GUIDES = [
  'assembly-guide-for-key-tail',
  'consolidated-manual-rev-09',
  'epic-things-app-user-manual',
  'ir-sensor-usage-guide-for-face-id',
  'outer-body-cable-management-guide',
  'remote-control-module-compatibility-guide',
];

const PRODUCT_GROUPS = PRODUCT_MANUALS.map((slug) => ({
  type: 'category' as const,
  label: slug.toUpperCase().replace(/-/g, '-'),
  link: { type: 'doc' as const, id: `${slug}/intro` },
  items: [{ type: 'autogenerated' as const, dirName: slug }],
}));

const REFERENCE_GROUP = REFERENCE_GUIDES.map((slug) => ({
  type: 'category' as const,
  label: slug
    .split('-')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join(' '),
  link: { type: 'doc' as const, id: `${slug}/intro` },
  items: [{ type: 'autogenerated' as const, dirName: slug }],
}));

const sidebars: SidebarsConfig = {
  manualsSidebar: [
    {
      type: 'category',
      label: '🛒 Product Manuals (26)',
      collapsed: false,
      items: PRODUCT_GROUPS,
    },
    {
      type: 'category',
      label: '📚 Installation & Reference Guides (6)',
      collapsed: false,
      items: REFERENCE_GROUP,
    },
  ],
};

export default sidebars;
