import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Use autogenerated sidebar from each manual's _category_.json
const sidebars: SidebarsConfig = {
  manualsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
